apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-environments-chart.fullname" . }}-config
  annotations:
    argocd.argoproj.io/sync-options: Skip=true
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
