apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app2-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Hola</title></head>
    <body><h1>Hola Mundo desde extraVolumes</h1></body>
    </html>
