image:
  repository: bitnami/nginx
  tag: latest

nginxServerBlock: |-
  server {
    listen 0.0.0.0:8080;
    root /app;
    index index.html;
  }

extraVolumes:
  - name: html
    configMap:
      name: hello-html

extraVolumeMounts:
  - name: html
    mountPath: /app
